const state={payment:null,activity:null};const $=id=>document.getElementById(id);const money=(n,c='USD')=>`${(Number(n||0)/100).toFixed(2)} ${c}`;const idem=()=>$("idempotency").value.trim()||`demo-${crypto.randomUUID()}`;
function notice(message,type=''){const e=$("notice");e.textContent=message;e.className=`notice ${type}`;}function errorMessage(e){return e?.error?.message||e?.message||'Request failed';}
async function request(path,options={}){const r=await fetch(path,{...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw b;return b;}
function setPayment(p){state.payment=p;$("paymentId").value=p.id;$("emptyState").classList.add('hidden');$("paymentDetails").classList.remove('hidden');$("heroPayment").textContent=p.id;$("heroStatus").textContent=p.status;$("stateTag").textContent=p.status;$("stateTag").className=`pill ${p.status==='CAPTURED'?'':'muted'}`;$("detailStatus").textContent=p.status;$("detailAmount").textContent=money(p.amount,p.currency);$("detailCaptured").textContent=money(p.captured_amount,p.currency);$("detailRefunded").textContent=money(p.refunded_amount,p.currency);$("detailProcessor").textContent=p.processor||'—';$("jsonOutput").textContent=JSON.stringify(p,null,2);refreshActivity();}
async function refreshActivity(){if(!state.payment)return;try{state.activity=await request(`/api/v1/payments/${state.payment.id}/activity`);renderActivity();}catch(e){notice(errorMessage(e),'error');}}
function renderActivity(){const a=state.activity||{};const events=[...(a.captures||[]).map(x=>({date:x.created_at,title:'Payment captured',detail:`${money(x.amount,state.payment.currency)} · ${x.processor_capture_id}`})),...(a.refunds||[]).map(x=>({date:x.created_at,title:'Payment refunded',detail:`${money(x.amount,state.payment.currency)} · ${x.processor_refund_id}`})),...(a.journals||[]).map(x=>({date:x.created_at,title:x.event_type.replaceAll('_',' '),detail:`Debit ${money(x.debit,x.currency)} · Credit ${money(x.credit,x.currency)}`}))].sort((x,y)=>new Date(x.date)-new Date(y.date));$("activity").innerHTML=events.length?events.map(x=>`<div class="event"><strong>${x.title}</strong><small>${new Date(x.date).toLocaleString()}</small><p>${x.detail}</p></div>`).join(''):'<div class="event"><strong>No activity yet</strong><p>Authorize or capture this payment to create an audit trail.</p></div>';}
async function run(label,path,body){try{notice(`${label}…`);const p=await request(path,{method:'POST',headers:{'Idempotency-Key':idem()},body:JSON.stringify(body||{})});setPayment(p);notice(`${label} completed`,'success');}catch(e){notice(errorMessage(e),'error');}}
$("createForm").addEventListener('submit',async e=>{e.preventDefault();const body={amount:Number($("amount").value),currency:$("currency").value.toUpperCase(),capture_method:'manual',reference:$("reference").value};await run($("flow").value==='pos'?'POS payment':'Payment created',$("flow").value==='pos'?'/api/v1/payments/pay':'/api/v1/payments',body);});
$("loadBtn").addEventListener('click',async()=>{if(!$("paymentId").value.trim())return notice('Enter a payment ID first','error');try{setPayment(await request(`/api/v1/payments/${$("paymentId").value.trim()}`));notice('Payment loaded','success');}catch(e){notice(errorMessage(e),'error');}});
$("authorizeBtn").addEventListener('click',()=>state.payment&&run('Authorization',`/api/v1/payments/${state.payment.id}/authorize`,{}));$("captureBtn").addEventListener('click',()=>state.payment&&run('Capture',`/api/v1/payments/${state.payment.id}/capture`,{amount:state.payment.authorized_amount-state.payment.captured_amount}));
$("refundBtn").addEventListener('click',()=>{if(!state.payment)return notice('Create or load a payment first','error');const amount=Number($("refundAmount").value);if(!amount||amount<1)return notice('Enter a positive refund amount','error');if(confirm(`Refund ${money(amount,state.payment.currency)}? This calls the payment API.`))run('Refund',`/api/v1/payments/${state.payment.id}/refund`,{amount});});$("refreshBtn").addEventListener('click',()=>state.payment&&request(`/api/v1/payments/${state.payment.id}`).then(setPayment).catch(e=>notice(errorMessage(e),'error')));
document.querySelectorAll('[data-amount]').forEach(b=>b.addEventListener('click',()=>{$("amount").value=b.dataset.amount;$("reference").value=b.dataset.reference;}));
